### editorconfig-vim ###
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

### vim-airline ###
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline_theme = 'deus'
let g:airline_symbols = {
\   'branch': "\uf418",
\   'dirty': "\u00b1",
\ }
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']

### colorschemes ###
[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
colorscheme codedark
'''
