### editorconfig-vim ###
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

### colorschemes ###
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
'''

### airline ###
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='gruvbox'
'''

### Gitのステータスをファイル左横に表示するやつ ###
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
nnoremap ]h <Plug>(GitGutterNextHunk)
nnoremap [h <Plug>(GitGutterPrevHunk)
nnoremap ghs <Plug>(GitGutterStageHunk)
nnoremap ghu <Plug>(GitGutterUndoHunk)
nnoremap ghp <Plug>(GitGutterPreviewHunk)
'''

### vim上でGit操作可能にするやつ ###
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <Leader>ga :G add %:p<CR><CR>
nnoremap <Leader>gc :G commit<CR><CR>
nnoremap <Leader>gs :G status<CR>
nnoremap <Leader>gp :G push<CR>
nnoremap <Leader>gd :G diff<CR>
nnoremap <Leader>gl :G log<CR>
nnoremap <Leader>glo :G log --oneline<CR>
nnoremap <Leader>gb :G blame<CR>
'''

### ファイラー ###
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
nnoremap <Leader>e <cmd>Fern . -reveal=%<CR>
'''

### fuzzy finder ###
[[plugins]]
repo = 'junegunn/fzf'
build = 'bash install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
nnoremap <Leader>z :FZF<CR>
nnoremap <Leader>r :Rg<SPACE>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>W :Windows<CR>
nnoremap <Leader>H :History<CR>
'''

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'
hook_add = '''
nnoremap <silent>//     <cmd>FzfPreviewLinesRpc<CR>
nnoremap <silent><C-f>  <cmd>FzfPreviewBufferLinesRpc<CR>
nnoremap <silent><C-p>  <cmd>FzfPreviewProjectFilesRpc<CR>

"nnoremap <silent>//     :BLines<CR>
"nnoremap <silent><C-f>  :Lines<CR>
"nnoremap <silent><C-p>  :Files<CR>
'''

### フォーカス移動を自由自在にするやつ ###
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
noremap  <Leader>f <Plug>(easymotion-bd-f)
nnoremap <Leader>f <Plug>(easymotion-overwin-f)
nnoremap <Leader>s <Plug>(easymotion-overwin-f2)
noremap  <Leader>L <Plug>(easymotion-bd-jk)
nnoremap <Leader>L <Plug>(easymotion-overwin-line)
noremap  <Leader>w <Plug>(easymotion-bd-w)
nnoremap <Leader>w <Plug>(easymotion-overwin-w)
'''
