### 補完のやつ ###
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'

### Railsプロジェクト用プラグイン ###
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']
hook_add = '''
let g:rails_no_abbreviations = 1
'''
