name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Setup
        run: curl -sL https://TB-takahiro-sakaguchi.github.io/dotfiles/install.sh | sh
